@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

package Model {
package "Subject System" #F4F6F6 {
    Enum Subject
    Class ScoreDict
    Class "{static}\nSubjectRegistry" as SubjectRegistry
}

Class Person
}


Subject *--> "1" ScoreDict
SubjectRegistry ..> Subject
Subject "*" --> "*" Person : enrolls >
ScoreDict --> "*" Person : scores >

@enduml
