@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":SetScoreCommand" as SetScoreCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Subject" as Subject MODEL_COLOR
participant ":ScoreDict" as ScoreDict MODEL_COLOR
participant "p:Person" as Person MODEL_COLOR
end box

SetScoreCommand -> Subject : setScore(p)
activate Subject

Subject -> Subject : validateEnrollment(p)
activate Subject
deactivate Subject

Subject -> ScoreDict : setScore(p, score)
activate ScoreDict

ScoreDict -> ScoreDict : scores.put(p, score)
activate ScoreDict
deactivate ScoreDict

ScoreDict --> Subject
deactivate ScoreDict

Subject --> SetScoreCommand
deactivate Subject

@enduml
